apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon
spec:
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: shopping-cart
        image: amay1794/shopping-cart
        ports:
         - containerPort: 80
